name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    env:
      SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.AFDIAN_ID }}
      SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}
      SPONSORKIT_AFDIAN_EXECHANGERATE: '1'
      AFDIAN_EXECHANGERATE: '1'
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build Sponsorkit
        run: nr build
        
      - name: Run Sponsorkit script
        run: node ./dist/cli.cjs

      - name: Upload
        uses: Teahouse-Studios/aliyun-oss-action@0.7
        with:
          KEY_ID: ${{ secrets.KEY_ID }}
          KEY_SECRET: ${{ secrets.KEY_SECRET }}
          BUCKET: frontend-wdljt
          LOCAL_PATH: ./sponsorkit/
          REMOTE_PREFIX: meme/sponsors/